services:
  - type: web
    name: truthlens
    env: python

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app
